Project.Performance.WebApp/Controllers/FunctionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project.Performance.Model;
using Project.Performance.Utility;
using Project.Performance.WebApp.ViewModels;

namespace Project.Performance.WebApp.Controllers
{
    public class FunctionsController : PerformanceBaseController
    {
        public ActionResult LoginServer(string serverUrl, string userName, string passWord)
        {
            try
            {
                LoginInfo loginModel = new LoginInfo(serverUrl, userName, passWord);
                bool isLogin = serverService.Login(loginModel);
                if (isLogin)
                {
                    return Json(new JsonMessage(true, "Log in successful!"), JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new JsonMessage(false, "The sign-in name or password does not match one in the Microsoft account system."), JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(new JsonMessage(false, "FAILED:" + ex.Message), JsonRequestBehavior.AllowGet);
            }
        }

        [ValidateInput(false)]
        public ActionResult ExecuteConfig(string models)
        {
            try
            {
                xmlModel = XMLHelper.GetModelFromXML(models);
                configService.ExecuteConfigTasks(xmlModel);
                return Json(new JsonMessage(true, "Execute action is triggered."), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new JsonMessage(false, "FAILED:" + ex.Message), JsonRequestBehavior.AllowGet);
            }
        }

        #region Refresh Functions
        public ActionResult GetResourceCreationStatus()
        {
            try
            {
                if (xmlModel != null && xmlModel.ResourcePoolModelList != null)
                {
                    List<ResourcePoolModel> models = xmlModel.ResourcePoolModelList;
                    if (models.Count > 0)
                    {
                        int all = models.Sum(item => item.Count);
                        int finish = configService.ResourceService.GetCount(xmlModel);
                        if (finish > all) { finish = all; }
                        double resourceCreationTime = 0; // configService.ResourceService.TimeRecord
                        return Json(
                            new
                            {
                                All = all,
                                Finished = finish,
                                CreationTime = resourceCreationTime,
                                Prefix = string.Join(",", models.Select(item => item.NamePrefix)),
                                PoolCount = finish,
                                log = LoggerHelper.Instance.Text
                            }, JsonRequestBehavior.AllowGet);
                    }
                }

                return Json(
                    new
                    {
                        All = 0,
                        Finished = 0,
                        CreationTime = 0,
                        Prefix = string.Empty
                    }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(new { data = e.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult GetProjectCreationStatus()
        {
            try
            {
                if (xmlModel != null && xmlModel.ProjectModelList != null)
                {
                    List<ProjectModel> models = xmlModel.ProjectModelList;
                    if (models.Count > 0)
                    {
                        List<ProjectCreationStatusViewModel> projStatus = new List<ProjectCreationStatusViewModel>();
                        int all = models.Sum(item => item.Count);
                        int finish = configService.ProjectService.GetCount(xmlModel);
                        projStatus.Add(new ProjectCreationStatusViewModel()
                        {
                            All = all,
                            NamePrefix = string.Join(",", models.Select(item => item.NamePrefix)),
                            Finished = finish
                        });

                        return Json(
                            new
                            {
                                ProjCreationInfo = projStatus,
                                Total = finish,
                                log = LoggerHelper.Instance.Text
                            }, JsonRequestBehavior.AllowGet);
                    }
                }

                return Json(
                    new
                    {
                        Total = 0,
                        ProjCreationInfo = new ProjectCreationStatusViewModel[0],
                    }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(new { data = e.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult GetLookupTableCreationStatus()
        {
            try
            {
                if (xmlModel != null && xmlModel.LookupTableModelList != null)
                {
                    List<LookupTableModel> models = xmlModel.LookupTableModelList;
                    if (models.Count > 0)
                    {
                        int all = models.Sum(item => item.Count);
                        int finish = configService.LookupTableService.GetCount(xmlModel);
                        double LookupTableCreationTime = 0;

                        return Json(
                            new
                            {
                                All = all,
                                Finished = finish,
                                CreationTime = LookupTableCreationTime,
                                Prefix = string.Join(",", models.Select(item => item.Name)),
                                log = LoggerHelper.Instance.Text
                            }, JsonRequestBehavior.AllowGet);
                    }
                }

                return Json(
                    new
                    {
                        All = 0,
                        Finished = 0,
                        CreationTime = 0,
                        Prefix = string.Empty
                    }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(new { data = e.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult GetCustomFieldStatus()
        {
            try
            {
                if (xmlModel != null && xmlModel.CustomFieldModelList != null)
                {
                    List<CustomFieldModel> models = xmlModel.CustomFieldModelList;
                    if (models.Count > 0)
                    {
                        int all = models.Sum(item => item.Count);
                        int finish = configService.CustomFieldService.GetCount(xmlModel);
                        double customFieldsCreationTime = 0;

                        return Json(
                        new
                        {
                            All = all,
                            Finished = finish,
                            Prefix = string.Join(",", models.Select(item => item.Name)),
                            CreationTime = customFieldsCreationTime,
                            log = LoggerHelper.Instance.Text
                        }, JsonRequestBehavior.AllowGet);
                    }
                }

                return Json(
                    new
                    {
                        All = 0,
                        Finished = 0,
                        CreationTime = 0,
                        Prefix = string.Empty
                    }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(new { data = e.Message }, JsonRequestBehavior.AllowGet);
            }
        }
        #endregion Refresh Functions

        #region Icon buttons functions
        [ValidateInput(false)]
        public ActionResult SaveFile(string model, string filename)
        {
            try
            {
                // Judge whether the format of xml is legal before saving 
                bool isValidated = XMLHelper.ValidateXMLFormat(model);
                if (!isValidated)
                {
                    return Json(new JsonMessage(false, "FAILED: The format of xml is incorrect!"), JsonRequestBehavior.AllowGet);
                }
                XMLHelper.SaveStringToFile(model, filename, GlobalUserName);
                return Json(new JsonMessage(true, "Save File Successfully"), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new JsonMessage(false, "FAILED:" + ex.Message), JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Import()
        {
            if (Request.Files != null && Request.Files.Count > 0)
            {
                try
                {
                    HttpPostedFileBase file = Request.Files[0];
                    return Json(new { data = XMLHelper.FormatXML(file.InputStream) }, JsonRequestBehavior.AllowGet);
                }
                catch (Exception ex)
                {
                    return Json(new JsonMessage(false, "FAILED:" + ex.Message), JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                return Json(new JsonMessage(false, "Import file is empty!"));
            }
        }

        public ActionResult OpenRemoteSampleFile()
        {

Project.Performance.WebApp/Views/View/_OpenFileDialog.cshtml
<div class="modal fade" id="OpenFileModal" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"
                        data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title" id="OpenModalLabel">
                    Import File
                </h4>
            </div>
            <div class="modal-body" style="text-align: center">
                <div class="form-group">
                    <div class="input-group" style="text-align: center">
                        <span class="input-group-addon">
                            <label class="control-label" style="width: 95px;">File:</label>
                        </span>
                        <input class="file" id="FileUpload" name="file_project" data-show-preview="false" type="file" />
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default"
                        data-dismiss="modal">
                    Close
                </button>

                <input id="submitimportfile" type="submit" class="btn btn-success" value="Submit" />
            </div>
        </div>
    </div>
</div>
<script>

    $("#FileUpload").change(function () {
        var formData = new FormData();
        var totalFiles = document.getElementById("FileUpload").files.length;
        for (var i = 0; i < totalFiles; i++) {
            var file = document.getElementById("FileUpload").files[i];
            formData.append("FileUpload", file);
        }
        $.ajax({
            type: "POST",
            url: '@Url.Action("Import","Functions")',
            data: formData,
            dataType: 'json',
            contentType: false,
            processData: false,
            beforeSend: function () {
                $("#c2").html("<center>load data...</center>");
            },
            success: function (data) {
                $("#c2").val(data.data + "\r\n");
                $("#c2").keyup();
                $("#c2").focus();
            },
            error: function (error) {
                alert("Please try again!");
            }
        });
    });
</script>

Project.Performance.WebApp/Views/View/_SaveFileDialog.cshtml
<div class="modal fade" id="SaveModal" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" style="width:120%">
            <div class="modal-header">
                <button type="button" class="close"
                        data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title" id="SaveModalLabel">
                    Enter FileName
                </h4>
            </div>
            <div class="modal-body">
                @Html.AntiForgeryToken()
                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon">
                            <label class="control-label" style="width:10%;padding-right:25px;padding-left:0px;">FilePath:</label>
                        </span>
                        <div class="form-control" style="text-align:left;width:53.24%">\\JIN-PT001\Config\UserFiles\@this.ViewBag.Data\</div>
                        <input id="filename" name="filename" type="text" class="form-control" style="border-left:none;width:100%">
                        <label class="control-label form-control" style="width:5px; border-right: none;">.xml</label>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default"
                        data-dismiss="modal">
                    Close
                </button>
                <input id="submitfilename" type="submit" class="btn btn-success" data-dismiss="modal" value="Submit" />
            </div>
        </div>
    </div>
</div>
<script>

    $("#SaveModal").on("shown.bs.modal", function () {
        $("#filename").val("");
    });
    $("#submitfilename").click(function () {
        $.ajax({
            url: '@Url.Action("SaveFile", "Functions")',
            dataType: "json",
            data: {
                model: $("#c2").val(),
                fileName: $("#filename").val()
            },
            type: "Post",
            success: function (json) {
                ShowJsonMessage(json);
            },
            error: function (XMLHttpRequest, message) {
                var json = { success: false, Message: message };
                ShowJsonMessage(json);
            }
        });
    });
</script>

Project.Performance.WebApp/Views/View/_SaveXml.cshtml
<div class="modal fade" id="SaveModal" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" style="width:120%">
            <div class="modal-header">
                <button type="button" class="close"
                        data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title" id="SaveModalLabel">
                    Enter FileName
                </h4>
            </div>
            <div class="modal-body">
                @Html.AntiForgeryToken()
                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon">
                            <label class="control-label" style="width:10%;padding-right:25px;padding-left:0px;">FilePath:</label>
                        </span>
                        <div class="form-control" style="text-align:left;width:53.24%">\\JIN-PT001\Config\UserFiles\@this.ViewBag.Data\</div>
                        <input id="filename" name="filename" type="text" class="form-control" style="border-left:none;width:100%">
                        <label class="control-label form-control" style="width:5px; border-right: none;">.xml</label>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default"
                        data-dismiss="modal">
                    Close
                </button>
                <input id="submitfilename" type="submit" class="btn btn-success" data-dismiss="modal" value="Submit" />
            </div>
        </div>
    </div>
</div>
<script>
    $("#SaveModal").on("shown.bs.modal", function () {
        $("#filename").val("");
    });
    $("#submitfilename").click(function () {
        $.ajax({
            url: '@Url.Action("SaveFile", "Functions")',
            dataType: "json",
            data: {
                model: $("#c2").val(),
                fileName: $("#filename").val()
            },
            type: "Post",
            success: function (json) {
                ShowJsonMessage(json);
            },
            error: function (XMLHttpRequest, message) {
                var json = { success: false, Message: message };
                ShowJsonMessage(json);
            }
        });
    });
</script>